"""summary cache table

Revision ID: 6c07018d8f9e
Revises: d976b1739a8d
Create Date: 2026-08-18 19:32:33.169740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c07018d8f9e'
down_revision: Union[str, Sequence[str], None] = 'd976b1739a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_cache',
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'text_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_cache')
    # ### end Alembic commands ###
