"""initial schema

Revision ID: 90d4a708ef6c
Revises: 
Create Date: 2026-08-07 23:08:48.648093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d4a708ef6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('analyses',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=True),
    sa.Column('source_preprocessor', sa.String(length=50), nullable=False),
    sa.Column('target_preprocessor', sa.String(length=50), nullable=False),
    sa.Column('source_output_level', sa.String(length=50), nullable=True),
    sa.Column('target_output_level', sa.String(length=50), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('dependency_expansion_depth', sa.Integer(), nullable=False),
    sa.Column('classifier_type', sa.String(length=50), nullable=False),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_project_id'), ['project_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.analysis_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('trace_links',
    sa.Column('trace_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('target_id', sa.String(length=500), nullable=False),
    sa.Column('target_content', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.analysis_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_links_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('artifact_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    with op.batch_alter_table('artifact_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_files_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_files_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_files_artifact_id'))

    op.drop_table('artifact_files')
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_links_analysis_id'))

    op.drop_table('trace_links')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_analysis_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_project_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
