"""embedding cache table

Revision ID: d976b1739a8d
Revises: 90d4a708ef6c
Create Date: 2026-08-07 23:29:21.538602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd976b1739a8d'
down_revision: Union[str, Sequence[str], None] = '90d4a708ef6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'text_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
